server: 
  address: 'tcp://:9091'

log:
  level: 'debug'

totp: 
  issuer: 'authelia.com'
    
identity_validation:
  reset_password:
    jwt_secret: # generate with docker run authelia/authelia:latest authelia crypto rand --length 128 --charset alphanumeric

authentication_backend:
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: 'deny'
  rules:
    - domain: '*.example.com'
      policy: 'one_factor'

session:
  secret: # generate with docker run authelia/authelia:latest authelia crypto rand --length 128 --charset alphanumeric
  cookies: 
    - name: 'authelia_session'
      domain: 'example.com'  
      authelia_url: 'https://authelia.example.com'
      expiration: '1 hour'
      inactivity: '5 minutes'

  redis:
    host: 'redis'
    port: 6379
    password: # generate with docker run authelia/authelia:latest authelia crypto rand --length 128 --charset alphanumeric

regulation:
  max_retries: 3 
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage: 
  encryption_key: # generate with docker run authelia/authelia:latest authelia crypto rand --length 128 --charset alphanumeric
  local:
    path: '/config/db.sqlite3' 

notifier:
  filesystem:
    filename: /config/notification.txt
